name: nimbus
description: A personal portfolio showcasing projects in Flutter development and Data Science.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Íconos y fuentes
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  feather_icons: ^1.2.0
  font_awesome_flutter: ^10.7.0

  # Ruteo automático
  auto_route: ^7.8.4

  # Responsive
  responsive_builder: ^0.7.0
  layout: ^1.0.3

  # Animaciones / UI
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  animated_text_kit: ^4.2.2
  flutter_staggered_grid_view: ^0.7.0
  visibility_detector: ^0.4.0+2

  # Utilidades
  url_launcher: ^6.2.5
  easy_localization: ^3.0.3
  go_router: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  auto_route_generator: ^7.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/images/icon_light.png
    - assets/images/icon_dark.png
    - assets/docs/Marvin_Zavaleta_Fullstack_Developer_EN.pdf
    - assets/docs/Marvin_Zavaleta_Fullstack_Developer_ES.pdf
